---
title: "Project Overview"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Rationale

Achieving the long-term vision of a resilient Sacramento-San Joaquin River Delta ecosystem requires meeting multiple goals simultaneously, including self-sustaining wildlife populations and thriving communities of people in an evolving landscape. However, to effectively plan and implement policies and land management decisions intended to achieve multiple goals, it is essential to be able to identify the potential trade-offs of changes to the landscape across multiple goals. Meeting this challenge would support effective policy and resource management decisions and address several science priorities identified in Science Action Agendas for the Delta.

To help meet this challenge, we built on our partnerships in the Delta and broader Central Valley and on our expertise in multiple-benefit conservation and avian ecology in agricultural landscapes to develop a science-based framework for projecting the net impact of landscape changes on multiple metrics representing goals for the Delta ecosystem. Our ultimate goals were to support communication among Delta community members about the projected benefits and trade-offs of proposed or anticipated changes to the landscape, to support effective decision-making and policy to reach the Delta Plan’s multiple goals. 

## Phase 1: 2019-2023

In Phase 1 of this project, *Trade-offs and Co-benefits of Landscape Change on Bird Communities and Ecosystem Services in the Sacramento–San Joaquin River Delta*, we established the foundations of our framework as the *DeltaMultipleBenefits* R package, now freely available for use and further development. We identified a suite of benefits categories and multiple quantifiable metrics to represent each category, which included compiling existing public data and analyzing thousands of existing bird survey data to build species distribution models for a suite of riparian landbird and waterbird species. We also worked with partners to identify two key drivers of landscape change of interest to investigate: habitat restoration and perennial crop expansion. We developed three alternative landscapes based on anticipated changes to the landscape from each driver in isolation and both drivers in combination, and we estimated the net impacts of each alternative landscape on each metric in comparison to a baseline landscape. This phase was funded by Proposition 1 Delta Water Quality and Ecosystem Restoration Program, Grant Agreement Number – Q1996022, administered by the California Department of Fish and Wildlife. All data, models, metrics, publications, and reports from Phase 1 are [available for download](articles/supporting_information.html).

## Phase 2: 2022-2026

In Phase 2 of this project, *Trade-offs and Co-benefits of Landscape Change in the Sacramento-San Joaquin River Delta: Phase II Tidal Wetlands and Restoration*, we are building on Phase 1 by incorporating new bird survey data in tidal wetlands and building new species distribution models to represent the habitat value of tidal wetland restoration. We are also working with partners to develop tidal wetland restoration scenarios for evaluation. This phase is funded by the Water Quality, Supply, and Infrastructure Improvement Act of 2014 (Proposition 1, CWC § 79707), grant agreement number Q2296017, administered by the California Department of Fish and Wildlife.

## Help us Envision the Next Phase

Our vision is to continue developing this framework to represent a more comprehensive range of goals for the Delta ecosystem and important metrics representing each goal, and support the evaluation of new scenarios and alternative landscapes as they are identified and developed. As an R package, this framework is designed to readily incorporate additional species, models, data, and metrics, and can be readily applied to new scenarios and alternative landscapes. 

We are currently seeking input on the next phase of development for this project:
-   What kinds of landscape changes would you be interested in having analyzed?
-   Which additional metrics or species would be useful to incorporate?
-   Which metrics should be refined with new data or better models?
-   Other suggestions?

Please contact us to collaborate on further development!
