#' Reclassify landscape rasters by SDM
#'
#' Prepare for fitting SDMs by reclassifying a landscape rasters according to
#' the classifications used by a specific species distribution model (SDM).
#'
#' This function is called by [python_focal_prep()] on a set of landscape
#' rasters generated by segregating an input landscape by class. It is not
#' intended to be called directly.
#'
#' @param landscape_stack SpatRaster created by [terra::rast()]
#' @param SDM The name of intended species distribution model: `"riparian"`,
#'   `"waterbird_fall"`, or `"waterbird_win"`
#'
#' @return SpatRaster with layers for each land cover class
#' @export
#'
#' @examples
#' r <- terra::rast(matrix(sample(c(0:4), size = 100, replace = TRUE),
#'         ncol = 10, nrow = 10)
#' levels(r) <- c('RIPARIAN_FOREST_POFR', 'RIPARIAN_FOREST_QULO', 'WETLAND', 'ORCHARD', 'VINEYARD')
#' layernames = terra::freq(r)$label
#' s = terra::segregate(r, other = 0)
#' names(s) = terra::freq(r)$label
#' example = reclassify_landcover(s, SDM = 'RIPARIAN')

reclassify_landcover = function(landscape_stack, SDM) {
  if (SDM == 'riparian') {
    c(# sum of all riparian subclasses
      terra::subset(
        landscape_stack,
        terra::names(landscape_stack)[grepl('RIPARIAN',
                                            terra::names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>% setNames('RIPARIAN'),
      # sum of all wetland subclasses
      terra::subset(
        landscape_stack,
        terra::names(landscape_stack)[grepl('WETLAND',
                                            terra::names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>% setNames('WETLAND'),
      # rename riparian and wetland subclasses
      terra::subset(landscape_stack,
                    c('WETLAND_MANAGED_PERENNIAL',
                      'RIPARIAN_FOREST_POFR',
                      'RIPARIAN_FOREST_QULO',
                      'RIPARIAN_FOREST_SALIX',
                      'RIPARIAN_FOREST_MIXED',
                      'RIPARIAN_SCRUB_MIXED',
                      'RIPARIAN_SCRUB_SALIX',
                      'RIPARIAN_SCRUB_INTRO')) %>%
        setNames(c('PERM', 'POFR', 'QULO','SALIX', 'MIXEDFOREST',
                   'MIXEDSHRUB', 'SALIXSHRUB', 'INTROSCRUB')),
      # sum of perennial crops, grassland/pasture, and other ag
      terra::subset(
        landscape_stack,
        terra::names(landscape_stack)[grepl('ORCH|VINE',
                                            terra::names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>% setNames('ORCHVIN'),
      terra::subset(
        landscape_stack,
        terra::names(landscape_stack)[grepl('PASTURE|GRASS',
                                            terra::names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>% setNames('GRASSPAS'),
      terra::subset(
        landscape_stack,
        terra::names(landscape_stack)[grepl('FIELD|GRAIN|ROW',
                                            terra::names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>% setNames('AG'),
      # keep rice, idle, urban, and water as-is
      terra::subset(landscape_stack, c('RICE', 'IDLE', 'URBAN', 'WATER'))
    )

  } else if (SDM == 'waterbird_fall') {
    c(
      # combine all riparian, perennial crops, managed wetlands,
      # other wetlands, and woodland/scrub
      terra::subset(
        landscape_stack,
        terra::names(landscape_stack)[grepl('RIPARIAN',
                                            terra::names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>% setNames('woodw'),
      terra::subset(
        landscape_stack,
        terra::names(landscape_stack)[grepl('ORCHARD|VINEYARD',
                                            terra::names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>% setNames('orch'),
      terra::subset(
        landscape_stack, c('WETLAND_TIDAL', 'WETLAND_OTHER')) %>%
        sum(na.rm = TRUE) %>% setNames('wet'),
      terra::subset(
        landscape_stack,
        terra::names(landscape_stack)[grepl('WETLAND_MANAGED',
                                            terra::names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>% setNames('duwet'),
      terra::subset(
        landscape_stack, c('WOODLAND', 'SCRUB')) %>% sum(na.rm = TRUE) %>%
        setNames('for'),
      # for fall, combine all grains
      terra::subset(
        landscape_stack,
        terra::names(landscape_stack)[grepl('GRAIN',
                                            terra::names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>% setNames('grain'),
      # keep others as-is and rename to match model inputs
      terra::subset(landscape_stack,
                    c('PASTURE_ALFALFA', 'PASTURE_OTHER', 'GRASSLAND',
                      'IDLE', 'RICE', 'FIELD_CORN', 'ROW', 'FIELD_OTHER',
                      'WATER', 'URBAN', 'BARREN')) %>%
        setNames(c('alf', 'ip', 'dryp', 'fal', 'rice', 'corn',
                   'row', 'field', 'water', 'dev', 'barren'))
    )
  } else if (SDM == 'waterbird_win') {
    c(
      # combine all riparian, perennial crops, managed wetlands,
      # other wetlands, and woodland/scrub
      terra::subset(
        landscape_stack,
        terra::names(landscape_stack)[grepl('RIPARIAN',
                                            terra::names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>% setNames('woodw'),
      terra::subset(
        landscape_stack,
        terra::names(landscape_stack)[grepl('ORCHARD|VINEYARD',
                                            terra::names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>% setNames('orch'),
      terra::subset(
        landscape_stack, c('WETLAND_TIDAL', 'WETLAND_OTHER')) %>%
        sum(na.rm = TRUE) %>% setNames('wet'),
      terra::subset(
        landscape_stack,
        terra::names(landscape_stack)[grepl('WETLAND_MANAGED',
                                            terra::names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>% setNames('duwet'),
      terra::subset(
        landscape_stack, c('WOODLAND', 'SCRUB')) %>% sum(na.rm = TRUE) %>%
        setNames('for'),
      # for winter, keep wheat separate from other grains
      terra::subset(
        landscape_stack, c('GRAIN&HAY_OTHER', 'GRAIN&HAY_WHEAT')) %>%
        setNames(c('grain', 'ww')),
      # keep others as-is and rename to match model inputs
      terra::subset(
        landscape_stack,
        c('PASTURE_ALFALFA', 'PASTURE_OTHER', 'GRASSLAND',
          'IDLE', 'RICE', 'FIELD_CORN', 'ROW', 'FIELD_OTHER',
          'WATER', 'URBAN', 'BARREN')) %>%
        setNames(c('alf', 'ip', 'dryp', 'fal', 'rice', 'corn',
                   'row', 'field', 'water', 'dev', 'barren'))
    )
  }
}
