#' Reclassify landscape rasters by SDM
#'
#' Prepare for fitting SDMs by reclassifying a landscape rasters according to
#' the classifications used by a specific species distribution model (SDM).
#'
#' This function is called by [python_focal_prep()] on a set of landscape
#' rasters generated by segregating an input landscape by class. It is not
#' intended to be called directly.
#'
#' @param landscape_stack SpatRaster created by [terra::rast()]
#' @param SDM The name of intended species distribution model: `"riparian"`,
#'   `"waterbird_fall"`, `"waterbird_win"`, or `"tima"`
#'
#' @return SpatRaster with layers for each land cover class
#' @importFrom stats setNames
#' @export
#'
#' @examples
#' #r <- terra::rast(matrix(sample(c(0:4), size = 100, replace = TRUE),
#' #         ncol = 10, nrow = 10)
#' #levels(r) <- c('RIPARIAN_FOREST_POFR', 'RIPARIAN_FOREST_QULO', 'WETLAND', 'ORCHARD', 'VINEYARD')
#' #layernames = terra::freq(r)$label
#' #s = terra::segregate(r, other = 0)
#' #names(s) = terra::freq(r)$label
#' #example = reclassify_landcover(s, SDM = 'RIPARIAN')

reclassify_landcover = function(landscape_stack, SDM) {
  if (SDM == 'riparian') {
    res = c(
      # sum of all riparian subclasses
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('RIPARIAN', names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>%
        stats::setNames('RIPARIAN'),
      # sum of all wetland subclasses
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('WETLAND', names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>%
        stats::setNames('WETLAND'),
      # sum of perennial crops, grassland/pasture, and other ag
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('ORCH|VINE', names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>%
        stats::setNames('ORCHVIN'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('PASTURE|GRASS',
                                     names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>%
        stats::setNames('GRASSPAS'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('FIELD|GRAIN|ROW',
                                     names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>%
        stats::setNames('AG'),
      # sum of open water and submerged veg
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('WATER|_SUB',
                                     names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>%
        stats::setNames('WATER')
    )
    # rename riparian and wetland subclasses if present:
    if ('WETLAND_MANAGED_PERENNIAL' %in% names(landscape_stack)) {
      res = c(res,
              terra::subset(landscape_stack, 'WETLAND_MANAGED_PERENNIAL') %>%
                stats::setNames('PERM'))
    }
    if (any(grepl('FOREST_POFR', names(landscape_stack)))) {
      res = c(res,
              terra::subset(landscape_stack,
                            names(landscape_stack)[grepl('RIPARIAN_FOREST_POFR', names(landscape_stack))]) %>%
                sum(na.rm = TRUE) %>%
                stats::setNames('POFR'))
    }
    if (any(grepl('RIPARIAN_FOREST_QULO|RIPARIAN_FOREST_QUER', names(landscape_stack)))) {
      res = c(res,
              terra::subset(landscape_stack,
                            names(landscape_stack)[grepl('RIPARIAN_FOREST_QULO|RIPARIAN_FOREST_QUER', names(landscape_stack))]) %>%
                sum(na.rm = TRUE) %>%
                stats::setNames('QULO'))
    }
    if (any(grepl('RIPARIAN_FOREST_SALIX', names(landscape_stack)))) {
      res = c(res,
              terra::subset(landscape_stack,
                            names(landscape_stack)[grepl('RIPARIAN_FOREST_SALIX', names(landscape_stack))]) %>%
                sum(na.rm = TRUE) %>%
                stats::setNames('SALIX'))
    }
    if (any(grepl('RIPARIAN_FOREST_MIXED', names(landscape_stack)))) {
      res = c(res,
              terra::subset(landscape_stack,
                            names(landscape_stack)[grepl('RIPARIAN_FOREST_MIXED', names(landscape_stack))]) %>%
                sum(na.rm = TRUE) %>%
                stats::setNames('MIXEDFOREST'))
    }
    if (any(grepl('RIPARIAN_SCRUB_MIXED', names(landscape_stack)))) {
      res = c(res,
              terra::subset(landscape_stack,
                            names(landscape_stack)[grepl('RIPARIAN_SCRUB_MIXED', names(landscape_stack))]) %>%
                sum(na.rm = TRUE) %>%
                stats::setNames('MIXEDSHRUB'))
    }
    if (any(grepl('RIPARIAN_SCRUB_SALIX', names(landscape_stack)))) {
      res = c(res,
              terra::subset(landscape_stack,
                            names(landscape_stack)[grepl('RIPARIAN_SCRUB_SALIX', names(landscape_stack))]) %>%
                sum(na.rm = TRUE) %>%
                stats::setNames('SALIXSHRUB'))
    }
    if (any(grepl('RIPARIAN_SCRUB_INTRO', names(landscape_stack)))) {
      res = c(res,
              terra::subset(landscape_stack,
                            names(landscape_stack)[grepl('RIPARIAN_SCRUB_INTRO', names(landscape_stack))]) %>%
                sum(na.rm = TRUE) %>%
                stats::setNames('INTROSCRUB'))
    }
    if (any(grepl('IDLE', names(landscape_stack)))) {
      res = c(res,
              terra::subset(landscape_stack,
                            names(landscape_stack)[grepl('IDLE', names(landscape_stack))]) |>
                sum(na.rm = TRUE) |>
                stats::setNames('IDLE'))
      }
    if (any(grepl('WATER|FLOATING_VEG|MUDFLAT', names(landscape_stack)))) {
      res = c(res,
              terra::subset(landscape_stack,
                            names(landscape_stack)[grepl('WATER|FLOATING_VEG|MUDFLAT', names(landscape_stack))]) |>
                sum(na.rm = TRUE) |>
                stats::setNames('WATER'))
      }
    if (any(c('RICE', 'URBAN') %in% names(landscape_stack))) {
      res = c(res,
              terra::subset(landscape_stack,
                            which(names(landscape_stack) %in%
                                    c('RICE', 'URBAN'))))
    }

  } else if (SDM == 'waterbird_fall') {
    res = c(
      # combine all riparian, perennial crops, managed wetlands,
      # other wetlands, and woodland/scrub
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('RIPARIAN', names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>%
        stats::setNames('woodw'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('ORCHARD|VINEYARD',
                                     names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>%
        stats::setNames('orch'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('WETLAND', names(landscape_stack)) &
                                 !grepl('WETLAND_MANAGED', names(landscape_stack))]) |>
        sum(na.rm = TRUE) %>%
        stats::setNames('wet'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('WETLAND_MANAGED',
                                     names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>%
        stats::setNames('duwet'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('WOODLAND|^SCRUB$', names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>% stats::setNames('for'),
      # for fall, combine all grains
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('GRAIN', names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>%
        stats::setNames('grain'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('IDLE', names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>%
        stats::setNames('fal'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('WATER|FLOATING_VEG|MUDFLAT', names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>%
        stats::setNames('water'),
      # keep others as-is and rename to match model inputs
      terra::subset(landscape_stack,
                    c('PASTURE_ALFALFA', 'PASTURE_OTHER', 'GRASSLAND',
                      'RICE', 'FIELD_CORN', 'ROW', 'FIELD_OTHER',
                      'URBAN', 'BARREN')) %>%
        stats::setNames(
          c('alf', 'ip', 'dryp', 'rice', 'corn', 'row', 'field',
            'dev', 'barren'))
    )
  } else if (SDM == 'waterbird_win') {
    res = c(
      # combine all riparian, perennial crops, managed wetlands,
      # other wetlands, and woodland/scrub
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('RIPARIAN', names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>%
        stats::setNames('woodw'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('ORCHARD|VINEYARD',
                                     names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>%
        stats::setNames('orch'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('WETLAND', names(landscape_stack)) &
                                 !grepl('WETLAND_MANAGED', names(landscape_stack))]) |>
        sum(na.rm = TRUE) %>%
        stats::setNames('wet'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('WETLAND_MANAGED',
                                     names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>%
        stats::setNames('duwet'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('WOODLAND|^SCRUB$', names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>% stats::setNames('for'),
      # for winter, keep wheat separate from other grains
      terra::subset(
        landscape_stack, c('GRAIN&HAY_OTHER', 'GRAIN&HAY_WHEAT')) %>%
        stats::setNames(c('grain', 'ww')),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('IDLE', names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>%
        stats::setNames('fal'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('WATER|FLOATING_VEG|MUDFLAT', names(landscape_stack))]) %>%
        sum(na.rm = TRUE) %>%
        stats::setNames('water'),
      # keep others as-is and rename to match model inputs
      terra::subset(
        landscape_stack,
        c('PASTURE_ALFALFA', 'PASTURE_OTHER', 'GRASSLAND',
          'RICE', 'FIELD_CORN', 'ROW', 'FIELD_OTHER',
           'URBAN', 'BARREN')) %>%
        stats::setNames(
          c('alf', 'ip', 'dryp', 'rice', 'corn', 'row', 'field',
            'dev', 'barren'))
    )
  } else if (SDM == 'tima') {
    res = c(
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('AG_ANNUAL|GRAIN|FIELD|ROW|IDLE|GRASSLAND|PASTURE|RUDERAL',
              names(landscape_stack))]) |>
        sum(na.rm = TRUE) |> stats::setNames('AGGRPAS'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('WETLAND_EMERGENT', names(landscape_stack))]) |>
        sum(na.rm = TRUE) |> stats::setNames('EMER'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('RIPARIAN_SCRUB_INTRODUCED', names(landscape_stack))]) |>
        sum(na.rm = TRUE) |> stats::setNames('INTR'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('WETLAND_LEPIDIUM', names(landscape_stack))]) |>
        sum(na.rm = TRUE) |> stats::setNames('LEPI'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('WETLAND_MEADOW', names(landscape_stack))]) |>
        sum(na.rm = TRUE) |> stats::setNames('MEAD'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('RIPARIAN_FOREST_MIXED', names(landscape_stack))]) |>
        sum(na.rm = TRUE) |> stats::setNames('MIXF'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('RIPARIAN_SCRUB_MIXED', names(landscape_stack))]) |>
        sum(na.rm = TRUE) |> stats::setNames('MIXS'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('WETLAND_PHRAGMITES', names(landscape_stack))]) |>
        sum(na.rm = TRUE) |> stats::setNames('PHRA'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('RIPARIAN_FOREST_POFR', names(landscape_stack))]) |>
        sum(na.rm = TRUE) |> stats::setNames('POFR'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('RIPARIAN_FOREST', names(landscape_stack))]) |>
        sum(na.rm = TRUE) |> stats::setNames('RFOR'),
      terra::subset(
        names(landscape_stack)[landscape_stack, grepl('RIPARIAN_SCRUB', names(landscape_stack))]) |>
        sum(na.rm = TRUE) |> stats::setNames('RSCR'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('RIPARIAN_FOREST_SALIX', names(landscape_stack))]) |>
        sum(na.rm = TRUE) |> stats::setNames('SALF'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('RIPARIAN_SCRUB_SALIX', names(landscape_stack))]) |>
        sum(na.rm = TRUE) |> stats::setNames('SALS'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('WETLAND_PICKLEWEED|WETLAND_SALTGRASS',
                                     names(landscape_stack))]) |>
        sum(na.rm = TRUE) |> stats::setNames('SALTPICK'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('WETLAND_TULE', names(landscape_stack))]) |>
        sum(na.rm = TRUE) |> stats::setNames('TULE'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('WATER|FLOATING_VEG|MUDFLAT',
                                     names(landscape_stack))]) |>
        sum(na.rm = TRUE) |> stats::setNames('WATER'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('WOODLAND|^SCRUB$|RUDERAL_WOODY',
                                     names(landscape_stack))]) |>
        sum(na.rm = TRUE) |> stats::setNames('WOODY'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('WETLAND.*_TIDAL',
                                     names(landscape_stack))]) |>
        sum(na.rm = TRUE) |> stats::setNames('TWET'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('WETLAND.*_NONTIDAL',
                                     names(landscape_stack))]) |>
        sum(na.rm = TRUE) |> stats::setNames('NWET'),
      terra::subset(
        names(landscape_stack)[landscape_stack, grepl('WETLAND',
                                                      names(landscape_stack))]) |>
        sum(na.rm = TRUE) |> stats::setNames('WETL'),
      terra::subset(
        landscape_stack,
        names(landscape_stack)[grepl('AG_PERENNIAL|ORCHARD|VINEYARD',
                                     names(landscape_stack))]) |>
        sum(na.rm = TRUE) |> stats::setNames('PNAG'),
      # keep some as-is
      terra::subset(
        landscape_stack, c('RICE', 'RUDRW', 'URBN', 'VERP'))
      )
  }
  return(res)
}
