#' Reclassify landscape rasters by SDM group
#'
#' Prepare for fitting SDMs by reclassifying a landscape rasters according to
#' the classifications used by a specific set of species distribution models
#' (SDM).
#'
#' Calls on internal datsets to crosswalk land cover classes encoded in the
#' provided landscape predictors expected by the selected set of SDMs. This
#' function is called by [python_focal_prep()] on a set of landscape rasters
#' generated by segregating an input landscape by class. It is not intended to
#' be called directly.
#'
#' Warnings are given if land cover classes are present in the landscape but are
#' excluded from model consideration, which may be a problem particularly if
#' they represent a large portion of the landscape. In this case, review the
#' corresponding internal dataset ([predictors_riparian()],
#' [predictors_waterbird_fall()], [predictors_waterbird_win()], or
#' [predictors_tima()]) to understand whether the model is expecting more
#' specific land cover classes or subclasses; the provided landscape may need to
#' be adjusted first.
#'
#' Warnings are also given if land cover classes are expected by the model but
#' are absent from the landscape. These land covers will be assumed absent from
#' the provided landscape and filled in with all 0 values, but these missing
#' land covers should be carefully reviewed to ensure they aren't excluded from
#' the landscape and model predictions unintentionally. If needed, the resulting
#' layers can be replaced manually before proceeding with [python_focal_run()].
#'
#' @param landscape SpatRaster created by [terra::rast()]
#' @param SDM The name of intended species distribution model: `"riparian"`,
#'   `"waterbird_fall"`, `"waterbird_win"`, or `"tima"`
#'
#' @return SpatRaster with separate layers for each land cover class included as
#'   a predictor in the selected SDM representing the presence (1) and absence
#'   (0)
#' @export
#' @seealso [key()], [predictors_riparian()], [predictors_waterbird_fall()],
#'   [predictors_waterbird_win()], or [predictors_tima()] for more details on
#'   the list of recognized landcover classes and subclasses and how they
#'   crosswalk to land cover predictors for each set of SDMs
#'
#' @importFrom utils data
#' @examples
#' library(DeltaMultipleBenefits)
#' #data(key)
#' r <- terra::rast(matrix(sample(c(11,19,71,72,90), size = 100, replace = TRUE),
#'          ncol = 10, nrow = 10)
#' landcover_presence = suppressWarnings(reclassify_landcover(r, SDM = 'riparian'))


reclassify_landcover = function(landscape, SDM) {

  levels(landscape) <- NULL
  landscape_vars = terra::freq(landscape)

  if (SDM == 'riparian') {
    pred <- DeltaMultipleBenefits::predictors_riparian
  } else if (SDM == 'waterbird_fall') {
    pred <- DeltaMultipleBenefits::predictors_waterbird_fall
  } else if (SDM == 'waterbird_win') {
    pred <- DeltaMultipleBenefits::predictors_waterbird_win
  } else if (SDM == 'tima') {
    pred <- DeltaMultipleBenefits::predictors_tima
  }

  # main set of classifications:
  crosswalk = dplyr::full_join(landscape_vars, pred, by = c('value' = 'CODE_NUM'))

  # check for excluded land covers: (present in landscape but excluded from model)
  excluded = crosswalk |> dplyr::filter(is.na(.data$PREDICTOR_NUM) & .data$count > 0) |>
    dplyr::mutate(prop = .data$count / sum(crosswalk$count, na.rm = TRUE))

  if (nrow(excluded) > 0) {
    print(excluded |> dplyr::select('CODE_NAME', 'count', 'prop'))
    warning("These land cover classes are present in the landscape but are not incorporated
into the selected SDM and will be excluded from the model predictions;
Check whether they can be replaced with more specific land cover classes or
subclasses, especially if they represent a significant proportion of the landscape.")
  }

  r = terra::classify(landscape,
                      rcl = crosswalk |> dplyr::select(from = 'value', to = 'PREDICTOR_NUM') |>
                        tidyr::drop_na(.data[['to']]),
                      others = NA)
  levels(r) <- crosswalk |> dplyr::select('PREDICTOR_NUM', 'PREDICTOR_NAME') |>
    tidyr::drop_na() |> dplyr::distinct() |> dplyr::arrange('PREDICTOR_NUM')

  # segregate
  layernames = terra::freq(r) |> dplyr::pull(.data[['value']])
  presence = terra::segregate(r, other = 0) |> stats::setNames(layernames)

  # add larger grouping predictors necessary for riparian and tima SDMs:
  if (SDM == 'riparian') {

    groupvars = c(
      terra::classify(landscape,
                      rcl = pred |> dplyr::filter(.data[['RIPARIAN']] == 1) |>
                        dplyr::select(from = 'CODE_NUM') |>
                        dplyr::mutate(to = 1),
                      others = 0),
      terra::classify(landscape,
                      rcl = pred |> dplyr::filter(.data[['WETLAND']] == 1) |>
                        dplyr::select(from = 'CODE_NUM') |>
                        dplyr::mutate(to = 1),
                      others = 0)
    )
    names(groupvars) = c('RIPARIAN', 'WETLAND')
    presence = c(presence, groupvars)

  } else if (SDM == 'tima') {

    groupvars = c(
      terra::classify(landscape,
                      rcl = pred |> dplyr::filter(.data[['NWET']] == 1) |>
                        dplyr::select(from = 'CODE_NUM') |>
                        dplyr::mutate(to = 1),
                      others = 0),
      terra::classify(landscape,
                      rcl = pred |> dplyr::filter(.data[['TWET']] == 1) |>
                        dplyr::select(from = 'CODE_NUM') |>
                        dplyr::mutate(to = 1),
                      others = 0),
      terra::classify(landscape,
                      rcl = pred |> dplyr::filter(.data[['WETL']] == 1) |>
                        dplyr::select(from = 'CODE_NUM') |>
                        dplyr::mutate(to = 1),
                      others = 0),
      terra::classify(landscape,
                      rcl = pred |> dplyr::filter(.data[['RFOR']] == 1) |>
                        dplyr::select(from = 'CODE_NUM') |>
                        dplyr::mutate(to = 1), others = 0),
      terra::classify(landscape,
                      rcl = pred |> dplyr::filter(.data[['RSCR']] == 1) |>
                        dplyr::select(from = 'CODE_NUM') |>
                        dplyr::mutate(to = 1),
                      others = 0))
    names(groupvars) = c('NWET', 'TWET', 'WETL', 'RFOR', 'RSCR')
    presence = c(presence, groupvars)

  }

  # check that all unique predictors are accounted for - may need rasters of all
  # 0 values if landscape contains none
  pred_unique = unique(stats::na.omit(pred$PREDICTOR_NAME))
  if(SDM %in% c('riparian', 'tima')) { # additional grouping vars
    pred_unique = c(pred_unique,
                    pred |> dplyr::select(5:dplyr::last_col()) |> names())
  }

  if (!all(pred_unique %in% names(presence))) {

    missing = pred_unique[!pred_unique %in% names(presence)]
    cat(missing)
    warning("These land cover classes are missing from the landscape but are expected by the
selected SDM. Creating rasters with all zero values to represent these land covers.
Check whether they have been excluded from the landscape unintentionally.")

    rnew = landscape
    rnew[!is.na(rnew)] <- 0 # raster with all zero values
    addme = list(rnew) |> rep(length(missing)) |> terra::rast()
    names(addme) = missing
    presence = c(presence, addme)

  } else {
    cat('Success: all required land cover classes are represented\n')
  }

  return(presence)
}
